[package]
name = "eeid"
type = "bin"
authors = [""]

[dependencies]
bignum = {tag = "v0.8.0-2", git = "https://github.com/zkpassport/noir-bignum"}
bigcurve = {tag = "v0.11.0-1", git = "https://github.com/zkpassport/noir_bigcurve"}
sha256 = { tag = "v0.2.1", git = "https://github.com/noir-lang/sha256" }
noir_ecdsa = { tag = "v0.2.9", git = "https://github.com/zkpassport/noir-ecdsa" }
sha512 = { tag = "master", git = "https://github.com/noir-lang/sha512" }
